-- Quadro com dados do cliente com impostos cAliasC5

SELECT 
	C5_NUM, 
	C5_CLIENTE, 
	C5_LOJACLI, 
	C5_TIPOCLI, 
	A1_NOME AS CLI_NOME, 
	A1_END AS CLI_ENDERECO, 
	A1_CEP AS CLI_CEP, 
	A1_MUN AS CLI_MUNICIPIO, 
	A1_EST AS CLI_UF, 
	A1_TEL AS CLI_TELEFONE, 
	A1_CGC AS CLI_CNPJ, 
	A1_INSCR AS CLI_IE, 
	A1_EMAIL AS CLI_EMAIL, 
	C5_EMISSAO AS EMISSAO, 
	C5_NUM AS PEDIDO, 
	C5_TIPO, 
	C5_CONDPAG AS CONDICAO_PAG, 
	CASE 
		WHEN C5_FECENT <> '' 
		THEN C5_FECENT 
		ELSE 
			CASE 
				WHEN C5_SUGENT <> '' 
				THEN C5_SUGENT 
				ELSE C6_ENTREG 
			END 
	END AS DT_ENTREG, -- Este dado não foi encontrado verificar se existe no cliente
	CASE 
		WHEN C5_FECENT <> '' 
		THEN 'C5_FECENT' 
		ELSE 
			CASE 
				WHEN C5_SUGENT <> '' 
				THEN 'C5_SUGENT' 
				ELSE 'C6_ENTREG' 
			END 
	END AS DT_ENTREGO, 
	A3_COD + ' - ' + A3_NOME AS REPRESENTANTE, 
	C5_TPFRETE, 
	C5_FRETE, 
	C5_SEGURO, 
	C5_DESPESA, 
	C5_DESCONT, 
	C5_PDESCAB, 
	C5_FRETAUT, 
	C5_TRANSP 
FROM 
	SC5010 SC5 
	INNER JOIN 
		SA1010 SA1 
		ON C5_CLIENTE = A1_COD 
		AND C5_LOJACLI = A1_LOJA 
		AND A1_FILIAL = '' 
		AND SA1.D_E_L_E_T_ = '' 
	INNER JOIN 
		SC6010 SC6 
		ON C5_NUM = C6_NUM 
		AND C6_FILIAL = '0101' 
		AND SC6.D_E_L_E_T_ = '' 
	LEFT JOIN 
		SA3010 SA3 
		ON C5_VEND1 = A3_COD 
		AND A3_FILIAL = '' 
		AND SA3.D_E_L_E_T_ = '' 
WHERE 
	C5_NUM = '000026' 
	AND C5_FILIAL = '0101' 
	AND SC5.D_E_L_E_T_ = '' 

-- Quadro de itens do pedido com impostos cAliasC6

SELECT 
	C5_NUM, 
	C6_NFORI, 
	C6_SERIORI, 
	SB1.R_E_C_N_O_ AS SB1_REC, 
	C6_ITEM AS ITEM, 
	C6_DESCONT AS DESCON, 
	C6_QTDVEN AS QUANT, 
	B1_QE AS EMB, 
	C6_UM AS UNIDADE, 
	B1_COD AS CODIGO_FAMA, 
	B1_PESO, 
	C6_PRODUTO, 
	C6_TES, 
	B1_DESC AS DESCRICAO, 
	B1_GRUPO, 
	C6_VALDESC, 
	C6_PRCVEN AS VALOR_UNI, 
	C6_VALOR AS VALOR_TOTAL, 
	C5_FRETE, 
	B1_GRUPO AS GRUPO_COD, 
	BM_DESC AS GRUPO_DESCRI, 
	'C6_UDCIDP + C6_UDCVEND + C6_UDCGPPD + C6_UDCCLI' AS DESCONTOS, 
	C5_CONDPAG, 
	E4_DESCRI, 
	'SBM_UMOLART' AS DESCONTOS_UMOLART 
FROM 
	SC5010 SC5 
	INNER JOIN 
		SC6010 SC6 
		ON C5_NUM = C6_NUM 
		AND C6_FILIAL = '0101' 
		AND SC6.D_E_L_E_T_ = '' 
	INNER JOIN 
		SB1010 SB1 
		ON C6_PRODUTO = B1_COD 
		AND B1_FILIAL = '' 
		AND SB1.D_E_L_E_T_ = '' 
	LEFT JOIN 
		SBM010 SBM 
		ON B1_GRUPO = BM_GRUPO 
		AND BM_FILIAL = '' 
		AND SBM.D_E_L_E_T_ = '' 
	LEFT JOIN 
		SE4010 SE4 
		ON C5_CONDPAG = E4_CODIGO 
		AND E4_FILIAL = '' 
		AND SE4.D_E_L_E_T_ = '' 
WHERE 
	C5_NUM = '000002' 
	AND C5_FILIAL = '0101' 
	AND SC5.D_E_L_E_T_ = '' 
ORDER BY 
	C5_NUM, C6_ITEM 

-- Quadro com dados do cliente com impostos cAliasC9

SELECT 
	C5_NUM AS PEDIDO, 
	C6_ITEM, 
	C9_DATALIB, 
	C5_EMISSAO AS EMISSAO 
FROM 
	SC5010 SC5 
	INNER JOIN 
		SA1010 SA1 
		ON C5_CLIENTE = A1_COD 
		AND C5_LOJACLI = A1_LOJA 
		AND A1_FILIAL = '' 
		AND SA1.D_E_L_E_T_ = '' 
	INNER JOIN 
		SC6010 SC6 
		ON C5_NUM = C6_NUM 
		AND C6_FILIAL = '0101' 
		AND SC6.D_E_L_E_T_ = '' 
	INNER JOIN 
		SC9010 SC9 
		ON C6_NUM = C9_PEDIDO 
		AND C6_PRODUTO = C9_PRODUTO 
		AND C6_ITEM = C9_ITEM 
		AND C9_FILIAL = '0101' 
		AND SC9.D_E_L_E_T_ = '' 
WHERE 
	C5_NUM = '000026' 
	AND C5_FILIAL = '0101' 
	AND SC5.D_E_L_E_T_ = '' 
ORDER BY 
	C5_NUM, C9_DATALIB DESC

-- Grupo de produto e condicao de pagamento

SELECT 
	B1_GRUPO AS GRUPO_COD, 
	BM_DESC AS GRUPO_DESCRI, 
	'C6_UDCIDP + C6_UDCVEND + C6_UDCGPPD + C6_UDCCLI' AS DESCONTOS, 
	SUM(C6_VALOR) AS VALOR_LIQUIDO, 
	0.00 AS IPI_VAL, 
	0.00 AS ST_VAL, 
	0.00 AS TOTAL_C_IMPOSTOS, 
	SUM(C6_QTDVEN * B1_PESO) AS PESO, 
	SUM(C6_QTDVEN) AS QTDE, 
	C5_CONDPAG, 
	E4_DESCRI, 
	'SBM_UMOLART' AS DESCONTOS_UMOLART, 
FROM 
	SC5010 SC5 
	INNER JOIN 
		SC6010 SC6 
		ON C5_FILIAL = C6_FILIAL 
		AND C5_NUM = C6_NUM 
		AND SC6.D_E_L_E_T_ = '' 
	INNER JOIN 
		SB1010 SB1 
		ON C6_PRODUTO = B1_COD 
		AND B1_FILIAL = '' 
		AND SB1.D_E_L_E_T_ = '' 
	INNER JOIN 
		SBM010 SBM 
		ON B1_GRUPO = BM_GRUPO 
		AND BM_FILIAL = '' 
		AND SBM.D_E_L_E_T_ = '' 
	INNER JOIN 
		SE4010 SE4 
		ON C5_CONDPAG = E4_CODIGO 
		AND E4_FILIAL = '' 
		AND SE4.D_E_L_E_T_ = '' 
WHERE 
	C5_FILIAL = '0101' 
	AND C5_NUM = '000026' 
	AND SC5.D_E_L_E_T_ = '' 
GROUP BY 
	B1_GRUPO, BM_DESC, C5_CONDPAG, E4_DESCRI

